### ISSUE TITLE
Signature spoofing

### ISSUE THREAD

**Issue by ghost** [cm-3470/android_device_samsung_kminilte#18]
Would be nice if someone could implement signature spoofing!?
https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing

**Comment by tobigun** [comment]
There are no plans at the moment to add signature spoofing. Selinux and safetynet now work out of the box.
Although this would provide support for microg it probably will cause issues safetynet to work. In addition it is a security hole. So the patch should not be applied by default.
