### ISSUE TITLE
running device/samsung/smdk3470-common/patch/apply.sh results in merge conflict

### ISSUE THREAD

**Issue by tomasz-ondrusz-chyp** [cm-3470/android_device_samsung_kminilte#8]
I have followed the steps as far as the patch command. When executing the .apply.sh the output looks like:

applying bootable_recovery to bootable/recovery
Applying: minui: disable blanking for devices that do not support it

applying frameworks_av to frameworks/av
Applying: av: Add samsung wfd service
Applying: fix "cannot locate symbol "_ZN7android16MediaBufferGroup14acquire_bufferEPPNS_11MediaBufferE" referenced by libwvm.so"

applying frameworks_native to frameworks/native
Applying: Revert "Remove Parcel::writeIntPtr."
Applying: Fix GPSd by adding a Lollipop compatibility SensorManager

applying hardware_ril to hardware/ril
Applying: ril: reintroduce changes necessary to make SIM detection work
Applying: ril: compatibility with LP libsec-ril.so

applying hardware_samsung_ril to hardware/samsung/ril
Applying: ril: add support for ss222 (G800F/Y/M)
Using index info to reconstruct a base tree...
M   ril/Android.mk
M   ril/libril/Android.mk
M   ril/libril/ril.cpp
Falling back to patching base and 3-way merge...
Auto-merging ril/libril/ril.cpp
Auto-merging ril/libril/Android.mk
CONFLICT (content): Merge conflict in ril/libril/Android.mk
Auto-merging ril/Android.mk
CONFLICT (content): Merge conflict in ril/Android.mk
Recorded preimage for 'ril/Android.mk'
Recorded preimage for 'ril/libril/Android.mk'
Failed to merge in the changes.
Patch failed at 0001 ril: add support for ss222 (G800F/Y/M)
The copy of the patch that failed is found in:
   /home/android/Documents/android_cyan/source/hardware/samsung/.git/rebase-apply/patch

Not sure how to proceed.

Many thanks

**Comment by CTXz** [comment]
I'm planning to move to my own patcher that will prevent issues like theese, I'm getting my s5 mini back tomorrow
