### ISSUE TITLE
Build CM with low RAM

### ISSUE THREAD

**Issue by flortsch** [cm-3470/android_device_samsung_kminilte#9]
Hello guys.

In the readme it says, that a machine with 8 GB RAM is needed for building CM. I would like to contribute to this project and build CM by myself, but unfortunately my machine has only 4 GB RAM.

Is it still somehow possible to build CM on my machine?
On the other hand, what about using an external CI service such as Travis?

Best regards
Florian

**Comment by Spookcity** [comment]
I built it with 4gb of ram fine.I do have 4.5gb of swap too tho.

**Comment by flortsch** [comment]
Okay, cool, I will check it out.
Thanks for your reply :)
